### ISSUE TITLE
 npm WARN deprecated @zeit/ncc@0.21.1: @zeit/ncc is no longer maintained. Please use @vercel/ncc instead.

### ISSUE THREAD

**Issue by huudy** [Dev-Thought/nx-plugins#64]
**Describe the bug**
so  I just ran 'npx ng add @dev-thought/nx-deploy-it' and received this:
`An unhandled exception occurred: npm WARN deprecated @zeit/ncc@0.21.1: @zeit/ncc is no longer maintained. Please use @vercel/ncc instead.`
**To Reproduce**
create new project with and try to run 

**Expected behavior**

**Logs**
`Installing packages for tooling via npm.
An unhandled exception occurred: npm WARN deprecated @zeit/ncc@0.21.1: @zeit/ncc is no longer maintained. Please use @vercel/ncc instead.
An error occurred while unpacking: Error: Unexpected end of data
npm WARN codelyzer@5.0.1 requires a peer of @angular/compiler@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.0.1 requires a peer of @angular/core@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.0.1 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 40
npm ERR! @dev-thought/pulumi-npm@1.5.0 postinstall: `node src/install-pulumi`
npm ERR! Exit status 40
npm ERR! 
npm ERR! Failed at the @dev-thought/pulumi-npm@1.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pablo/.npm/_logs/2020-12-07T14_23_22_155Z-debug.log
Package install failed, see above.
See "/tmp/ng-mY2VJ2/angular-errors.log" for further details.`
**Application type:**
[x] Angular
[] NestJS

**Provider:**
[x] AWS
[] Azure
[] Google Cloud Platform

**nx-deploy-it version**
0.2.2

**Additional context**
Could you please take a look? probably an update of that  @zeit/ncc might help

**Comment by MitkoTschimev** [comment]
Thx for the report! I will take care of it ;)

**Comment by MitkoTschimev** [comment]
Fixed with 1.4.3

**Comment by huudy** [comment]
Great man! Really great tool, love at first use ;) thanks for your work!
