### ISSUE TITLE
Deploy with Custom Webpack

### ISSUE THREAD

**Issue by kleberksms** [Dev-Thought/nx-plugins#66]
**Describe Feature**
Create an option to deploy with custom webpack builders for angular build facade.

**To Reproduce:**
Always when I need to use a custom webpack I should change application-type.js to deploy.
I have tested only for Azure.
https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack

**Solution:**

Add
```
function isAngularCustomWebpack(targets: TargetDefinitionCollection): boolean {
  const build = getTarget(targets, 'build');
  if (!build) {
    return false;
  }
  return build.builder === '@angular-builders/custom-webpack:browser';
}

export function getApplicationType(
  targets: TargetDefinitionCollection,
  host?: Tree
): ApplicationType {
  if (!targets) {
    return null;
  }

  if (isNestJS(targets, host)) {
    return ApplicationType.NESTJS;
  }
  if (isExpressJS(targets)) {
    return ApplicationType.EXPRESS;
  }

  if (isAngularUniversal(targets)) {
    return ApplicationType.ANGULAR_UNIVERSAL;
  }
  if (isAngular(targets)) {
    return ApplicationType.ANGULAR;
  }
  if (isAngularCustomWebpack(targets)) {
    return ApplicationType.ANGULAR;
  }
  if (isReact(targets)) {
    return ApplicationType.REACT;
  }

  return null;
}

```
**Aplication Type:**
[x] Angular
[] NestJS

**Prodiver:**
[] Azure
[] AWS
[] Google Cloud Platform

**Additional:**
The package is not an official package, maybe other option as a parameter can be better to run a deploy

**Comment by MitkoTschimev** [comment]
Thanks for the contribution @kleberksms !

Integration is done in version 1.5.0
