### ISSUE TITLE
Problem with installation on Windows 10

### ISSUE THREAD

**Issue by zdenekmikel** [Dev-Thought/nx-plugins#68]
**Describe the bug**
I just ran 'npx ng add @dev-thought/nx-deploy-it' and received this
Unfortunately, your platform and architecture (win32, x64) isn't currently supported by Pulumi. Please uninstall this package.

**To Reproduce**
Install on Windows 10

**Expected behavior**
successful installation

**Logs**
npm ERR! code ELIFECYCLE
npm ERR! errno 10
npm ERR! @dev-thought/pulumi-npm@1.5.0 postinstall: `node src/install-pulumi`
npm ERR! Exit status 10
npm ERR!
npm ERR! Failed at the @dev-thought/pulumi-npm@1.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Application type:**
[x] Angular
[x] NestJS

**Provider:**
[] AWS
[] Azure
[x] Google Cloud Platform

**nx-deploy-it version**
0.2.2

**Additional context**
Pulumi supports Win 10.

**Comment by MitkoTschimev** [comment]
Thanks for the report and I will try to figure out whats the problem. Maybe I will need a bit of support from you but I will come back to you ;)

**Comment by MitkoTschimev** [comment]
Move the bug to https://github.com/Dev-Thought/pulumi-npm/issues/6

**Comment by MitkoTschimev** [comment]
Should be fixed with https://github.com/Dev-Thought/pulumi-npm/issues/6
