### ISSUE TITLE
Nx 11 workspace error while running deploy

### ISSUE THREAD

**Issue by Doginal** [Dev-Thought/nx-plugins#69]
**Describe the bug**
Clean nx 11 mono repo, added deploy-it and configured correctly. 

When I run `yarn ng deploy appName` the CLI throws this error 

```
workspace_1.readWorkspaceConfigPath is not a function
```

I did some digging into @nrwl/workspace and it looks like in NX 11 readWorkspaceConfigPath was remove and replace with getWorkspace within the devkit. 

**Application type:**
[x] Angular
[x] NestJS

**Provider:**
[x] AWS
[] Azure
[] Google Cloud Platform

**nx-deploy-it version**
1.5.0

**Comment by MitkoTschimev** [comment]
Thx for digging into it!
I will provide a new major version for nx11+ releases when I fixed everything ;)

**Comment by Doginal** [comment]
changing line 83 in workspace.js within my node_modules from: 
```
const workspaceConfig = readWorkspaceConfigPath();
```
to
```
const workspaceConfig = require(getRealWorkspacePath()+ '/angular.json');
```
OR
```
const workspaceConfig = require(getRealWorkspacePath() + '/workspace.json');
```

seems to have bypassed the error and started the deploy process :D Definitely not the correct way to get the workspace JSON but it's a quick hack to get my mono repo to deploy! 

I haven't fully deployed my project yet, but I will make sure to update if it does deploy correctly!

**Comment by MitkoTschimev** [comment]
Unfortunately, it's not that easy :(
The workspace layout changed from v1 to v2 and there are more changes necessary to be prepared for next releases.
I'm on it but it will take a bit longer ;)

Sorry about that!

**Comment by Doginal** [comment]
All good

[here](https://github.com/Doginal/nx-11-deploy-it-testing) is the nx 11 angular + nestjs mono repo we talked about on slack it has two libs, one buildable one not for nestjs. 

Lmk if you want other libs in here for testing!

Thanks

**Comment by MitkoTschimev** [comment]
Ok version 2.0.0 is published now and works with nx 11+
For all versions smaller than nx 11 you need to use the latest 1.x.x version

In the end, I found an easy way to make it compatible but the big refactoring still needs to be done to be prepared for workspace version 2

#70
